readme.md
If the bot hasn't loaded the player, such as being too far away or on certain server proxies, the bot would crash when trying to find the entity.
=> Fixed bug in example which would crash client if player can't be seen.

index.js
As per discussion on PR #19: Improved tool selection using `digTime`.
I'm open to suggestions on improving the new `itemIsTool` check, feels like there should be a better way to check than string comparisons, but I think it works as a first pass anyhow.
Tested with the `example/test.js` bot on `1.16.1` and seems to work
=> Tool selection improvements

index.js
Currently, there is no way to specify the timeout variable without directly editing the source files. This variable should be exposed to allow users to define their own timeouts.
The default value of 40ms only discovers roughly 250 nodes on my machine (and visits a mere 40), which is only useful in very short distances. (I think this part is slow as the interpreter needs some time to cache the code)
```js
{
status: 'timeout',
cost: 0,
time: 40.84438499994576,
visitedNodes: 43,
generatedNodes: 262,
path: []
}
```
I have many instances where I would like to specify much larger timeouts for very far distances, and this is simply not possible at current.
=> Exposed ThinkTimeout Variable

.gitignore, index.d.ts
this PR makes the typings for the module slightly more accurate
- exports the module as an interface, not as a class, because in its current state this module does not export a class
- adds all properties to the `Movements` class
- no longer has the `PathNode` class as the module does not export it and it is not referenced anywhere
- no longer exports the `MoveBlockChange` interface as it is not referenced anywhere
- exports the `Move` class as an interface instead, again because the module does not export this class
- renames the `Result` interface to `ComputedPath` to give a better indication of what it is
- makes use of the `public` keyword to indicate that everything is public
- makes the `Goal` class abstract to more obviously indicate these methods must be implemented by an …
=> typings: make typings more accurate

lib/movements.js
This is a partial fix for #53.
In this case, `b` can only be null if `pos` is also null, meaning accessing `pos.y` in this if-statement is never allowed and will always cause a crash.
Assuming `pos.y` is 0 fixes the crash.
While https://github.com/PrismarineJS/mineflayer/issues/1405 needs to be fixed for pathfinding to work correctly, this will at least stop the crashing when dealing with null blocks. Once the skin restorer plugin issue is fixed, #53 can be closed as well.
=> Fixed crash with null positions

.gitignore, index.d.ts, index.js
This PR adds 2 new properties `movements` and `goal`, these are read-only getters
marking as draft until #66 is merged then these can be added to the new typings
resolves #57
=> feat: expose movements and goal

lib/movements.js
Fixes issue #54
The Bot tries to jump up inside the water block to place a Block below it. 
This is not possible with standard Minecraft physics as the player cannot jump high enough out of the water block to place a block below itself.
=> Bot getting stuck in Water fix

index.js
Hi guys i detect issue with pathfinder.isMining()
When you cancel the pathfinder with 
"bot.pathfinder.setGoal(null)"
The isMining is reset to false instantaly, but this is fake,
if you have any code with 
```js
bot.pathfinder.setGoal(null)
if(pathfinder.isMining() === false)
{
// all time is enters on code
}
```
In reallity must be wait event is triggered "diggingAborted"
For that i made a event listener to wait until diggingAborted is triggered and then change digging false
On my tests isMining work better, now no have bugs with move + dig
=> Fixed bug for detect when mining is stopped correctly

index.js, lib/movements.js, readme.md
Some anti-cheat plugins don't allow the placing of blocks if the face the block is being placed agains faces await from the current position. This could break the ability for the Bot to build bridges. The bot can now sneak to the edge of the block to place its next block and automatically return to a previous position if the next block to place would be obstructed by the bot.
https://youtu.be/c4Tvc0L0u_0
=> Legit bot bridging

index.js
LOSWhenPlacingBlocks is defined on pathfinder, not the bot. See line 38 of this file for reference.
=> Fix reference to LOSWhenPlacingBlocks

lib/goals.js
GoalPlaceBlock does not check if the raycast opperation hit the right block face when looking for reference blocks to place a block against. This is an issue as anti cheat plugins do raycast calculations on black placement and refuse transactions when the block face is not visible.
=> Fixed raycasting not considering block face

examples/example.js, index.d.ts, index.js, readme.md
This function is different to `setGoal(null)` as it tries to stop when the bot reaches a safe position. Due to errors while building and bridging it also stops on errors like a placing errors or path resets due to block updates, chunk loading etc. 
When resetting paths the bot cancels its velocity so setGoal(null) can cause the bot to fall off edges or fail jumps.
=> Function to stop path finding when safe

index.d.ts
When compiling other typescript projects with `tsc`  was getting the errors below. Addressing them because it causes tsc to exit nonzero.
```
node_modules/mineflayer-pathfinder/index.d.ts:151:16 - error TS2515: Non-abstract class 'GoalPlaceBlock' does not implement inherited abstract member 'hasChanged' from class 'Goal'.
151   export class GoalPlaceBlock extends Goal {
~~~~~~~~~~~~~~
node_modules/mineflayer-pathfinder/index.d.ts:151:16 - error TS2515: Non-abstract class 'GoalPlaceBlock' does not implement inherited abstract member 'heuristic' from class 'Goal'.
151   export class GoalPlaceBlock extends Goal {
~~~~~~~~~~~~~~
node_modules/mineflayer-pathfinder/index.d.ts:151:16 - error TS2515: Non-abstract class 'GoalPlaceBlock' does not implement inherited abstract member 'isEnd' from …
```
=> Fix compile errors in index.d.ts

index.js, lib/lock.js
Should resolve the issue of the bot placing wrong blocks as scaffolding and trying to place blocks at the same time.
=> bot sometimes placing wrong block as scaffolding

lib/movements.js
Fixes the bot getting stuck in this Scenario:
When moving from the diamond block to the gold block it gets stuck as it tries to jump over the wall even tho it cannot make that jump. By stuck I mean not moving at all as the simulations of the jump fail causing the bot to not move at all.
=> Fix diagonal move not considering collision height when jumping up diagonally

lib/movements.js
They slow down bots, and also could be a trap for mobs/players.
=> Avoid Cobwebs

index.d.ts, lib/goals.js
GoalBreakBlock is misleading. It just looks at a exposed block face.
Additionally, "GoalBreakBlock" is also useful for properly opening chests.
This renames GoalBreakBlock to GoalLookAtBlock, also exposing GoalBreakBlock for backward compatibility.
=> Clarification of GoalBreakBlock

lib/goto.js
Calling `Pathfinder#stop` while a path from `Pathfinder#goto` is being travelled causes it to stop indefinitely, making it throw an error when `Pathfinder#goto` is called again.
I've added the `path_stop` listener to `Pathfinder#goto`, which will clean up when called while the path is still being used.
=> cleanup Pathfinder#goto when Pathfinder#stop is called

index.d.ts, lib/goto.js
pathfinder#goto now throws if stopped. 
The path hasn't been completed, and as such, the call should not indicate success.
=> Indicate path stopped to caller

examples/blockInteraction.js, index.d.ts, lib/goals.js, readme.md
This should make it less confusing when digging and placing blocks. As now both GoalPlaceBlock and GoalLookAtBlock take similar augments.
I also updated the example for placing and breaking blocks. It now includes an example off how to mine blocks.
=> Refactor GoalLookAtBlock and depricate GoalBreakBlock

index.js
I think this check is wrong. It should only skip the optimization when exclusionArea is used not when it is not used. This might also be missing exclusionAreaPlace and exclusionAreaBreak but I am 90% sure that that dose not matter anyway as the optimization step cannot introduce any new blocks to break or place.
=> Fix path optimization check

index.js
`blockUpdate` may fire with `oldBlock` as null causing `isPositionNearPath` to crash
=> Add missing null check

index.d.ts, index.js, lib/movements.js
When starting a path on a none full block the resulting calculations will start inside the block the bot is standing **in** and not the block the bot is standing **on**
=> Path start fix

index.d.ts, index.js, lib/goto.js, readme.md
This pr adds some more options to the goto utility. 
Current issue: If the allowPartial option is used and there is no complete path goto won't resolve. This is an issue in pathfinder where it can get stuck with an active goal.
=> Add more goto options

index.d.ts, readme.md
- Add missing isValid method on Goal class
- Make hasChanged none abstract
- Add Goal class documentation
All methods in `Goal` have a default implementation off all methods making re implementing them redundant if they do not change from the default values. `heuristic` and `isEnd` are still abstract as it should be discouraged to make Goal instances that do not implement there own heuristic and isEnd method.
=> Change Goal typing and add Goal Documentation

lib/movements.js, readme.md
Wheat is not an unbreakable block and should not be avoided. There are other crops similar to wheat, such as potatoes or carrots. Farmland (not wheat) may be harmed by jumping rather than by moving. However, categorizing wheat as an unbreakable item is misleading, as it does not require breaking it to pass, moreover, it can be broken if needed. There were issues reported as #102 and #129, and the special handling of wheat (rather than carrot and potato) is still misleading. This issue can be solved in each of the applications by movements.blocksToAvoid.delete(wheat) and movements.blocksCantBreak.delete(wheat), but these default settings cannot be justified, they are confusing and not explicit, it was hard to understand from the documentation why they were implemented and why a bot stuck …
=> Wheat is not an unbreakable block and should not be avoided - but added misleadingly to the two lists

lib/goals.js
Same fix I did for mineflayer's visible face math. ([PR](https://github.com/PrismarineJS/mineflayer/pull/2801))
The math for getting the position relative to the center of the block was off by a bit.
=> Block face position fix

index.d.ts
Hey Hey :)
Seems like there were missing typescript deffinitions for ``GoalCompositeAny`` and ``GoalCompositeAll``.
[Look at](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/goals.js#L228) and [here](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/lib/goals.js#L266).
The doc saying that you can pass array of goals [too](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/readme.md?plain=1#L374).
This PR adds missing constructor deffinitions for Typescript.
=> Added missing constructor definitions for GoalComposite[Any/All] 

index.d.ts, lib/movements.js, readme.md
canOpenDoors is buggy and seam to not work on some server implementation.
It was also missing documentation and type definitions.
=> Change canOpenDoors default value to false

index.js
On a block update, the current path gets reset if the block updated is near one of the path nodes.
On optimized paths, the distance between path nodes may be significant. Checking only the path nodes themselves may mean that a block update along the line between two path nodes gets ignored when it could impact the path.
Consider a bot that farms pumpkins - after breaking many blocks and picking them up, it could try to navigate to the next part of the farm to harvest - across flat open land, this could easily be a straight line that optimizes nicely. But, a pumpkin could suddenly grow and block the bot. Currently, if the pumpkin didn't grow right at the beginning or end of that path segment, it would be ignored, and the bot may get stuck on the newly grown pumpkin.
Improve …
=> Fix block update resets for optimized paths

history.md, package.json
Since version 4.12.0 of Mineflayer, a warning message appears when using the deprecated event "physicTick" but the latest version of Mineflayer-pathfinder does use the deprecated event even though a pull request fixed it, that's why I would like to make a new release so this plugin won't trigger the warning message anymore.
=> Release 2.4.5
