PrismarineJS/mineflayer-pathfinder

readme.md
=> Add more details to README

readme.md
Minor change which avoids a crash.
=> Fix constant

index.js
Added a few simple API functions for checking the current pathfinding state.
=> Added some utility API functions.

index.d.ts
Should cover most all classes and use cases.
=> Created typescript headers.

lib/goals.js
This is to allow users to define their own goal functions.
=> Made goal public export

.gitpod.yml, readme.md
I like gitpod because it's one click to start testing things
=> gitpod.yml + gitpod badge

index.js
Closes https://github.com/Karang/mineflayer-pathfinder/issues/49
=> Added default movements out-of-the-box

index.js
Closes https://github.com/Karang/mineflayer-pathfinder/issues/48
=> Added goal updated event.

index.js, lib/goto.js
This function reduces a lot of boilerplate code by nicely wrapping the code functionality inside a nice, single function with a callback.
Usage:
```js
bot.pathfinder.goto(new GoalBlock(1, 2, 3), (err) => {
if (err) bot.chat(err)
else bot.chat("I'm here!")
})
```
=> Added Goto utility function

lib/movements.js
=> Added canDig variable

history.md
Added entries for every update made to pathfinder since released.
=> Created history.md

readme.md
A quick and dirty wiki to make the plugin much easier to use for beginnners
=> API in the readme

lib/movements.js, readme.md
This should theoretically work but I haven't tested it yet in action
=> Set every non diggable block automatically from mcdata

examples/test.js, index.d.ts, index.js, lib/astar.js, lib/move.js, lib/movements.js, lib/physics.js
Inspired by https://github.com/mat-1/mineflayer-baritone with some simplifications.
Closes #80, #70, #14, #44
=> Replace control logic by physic simulation, sprint and advanced parkour

lib/movements.js
=> Added +1 to movement cost when going forward and up 1 block.

readme.md
#145 I added )} at the end of example code in the README file. PrismarineJS/mineflayer-pathfinder team, please let me be a  contributor to your repository.
=> Added )} at the end of example code

lib/movements.js
Why: It was not correct. See https://minecraft.fandom.com/wiki/Coordinates#Coordinate_system
=> Fix cardinal direction comments

examples/callback.js, examples/promise.js, readme.md
Add examples that explain how to use pathfinder.goto
=> Add 2 examples

readme.md
=> readme fixed typo on goalY (z instead of y)

.gitignore, examples/example.js, history.md, index.d.ts, lib/goals.js, readme.md
This goal places the bot in a position were it is able to break a specific block. The block to break only has to be in line of sight and in reach. I added an example to the examples/example.js
=> Add GoalBlockBreak

examples/example.js, index.d.ts, lib/goals.js, readme.md
Stay consistent with naming convention
=> Goalblockbreak rename

index.js
Get pathfinder ready for mineflayers callback removal
=> Removed callbacks form function use

index.d.ts, lib/movements.js, readme.md
=> Add infiniteLiquidDropdownDistance boolean

examples/exclusionArea.js, index.d.ts, index.js, lib/movements.js, readme.md
=> Exclusion area

history.md, package.json
=> Release 1.10.0

history.md, package.json
=> Release 2.0.0

index.d.ts, index.js, readme.md
Exposes a way to have pathfinder calculate a path from any given point to a given goal. Including path optimization and starting position abstraction.
=> Add getPathFromTo

index.js
When standing on a none full blocks isEnd on the current goal can fail getting the bot stuck
=> Fix bot not finishing paththing

index.js
Add sneak action when bot tries to place block on interactable blocks
Issue related: https://github.com/PrismarineJS/mineflayer-pathfinder/issues/313
=> Added "sneak" on interact blocks to avoid open it

readme.md
=> reword .stop() for more clarity

.github/workflows/ci.yml
=> Update to node 22
